spring:
  profiles:
    active: dev
server:
    port: 8080
jwt:
    secret: ${JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: dev
server:
    port: 8081
jwt:
  secret: ${JWT_SECRET}
---
spring:
  config:
    activate:
      on-profile: prod
server:
    port: 8082
jwt:
  secret: ${JWT_SECRET}